text = input("Enter a data: ")
print("Lowercase: ", text.lower())
print("Uppercase: ", text.upper())
print("Capitalize text: ", text.capitalize())
print("Title text: ", text.title())
split = text.split()
print("words: ", split)
print("Alphabetic first word: ", sorted(split)[0])
print("Alphabetic last word: ", sorted(split)[-1])